language: go
go:
- 1.x

env:
  global:
    - LANG="zh_CN.UTF-8"
matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
      addons:
        apt:
          packages:
            - graphviz
            - python3

script:
  - sudo snap install hugo
  - sudo snap refresh hugo
  - bash deploy.sh

after_success:
  - cd public ;

    echo "owent.net" > CNAME ;

    git init ;

    git lfs install ;

    git lfs track "*.ico" ;

    git lfs track "*.png" ;

    git lfs track "*.jpg" ;

    git lfs track "*.jpeg" ;

    git lfs track "*.bmp" ;

    git lfs track "*.zip" ;

    git lfs track "*.tar.*" ;

    git lfs track "*.tgz" ;

    git lfs track "*.vsd*" ;

    git lfs track "*.doc*" ;

    git lfs track "*.xls*" ;

    git add . ;

cache: 
  apt: true
  ccache: true

deploy:
  provider: pages
  local_dir: public
  repo: owent/blog-website
  target_branch: master
  # keep_history: true
  keep_history: false
  fqdn: owent.net
  project_name: "I'm OWenT"
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    all_branches: true

notifications:
  email:
    recipients:
      - admin@owent.net
      - owt5008137@live.com
    on_success: change
    on_failure: change
  irc:
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"