language: go
go:
- 1.x

env:
  global:
    - LANG="zh_CN.UTF-8"
matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
      addons:
        apt:
          packages:
            - graphviz
            - python3

script:
  - sudo snap install hugo
  - sudo snap refresh hugo
  - bash deploy.sh

after_success:
  - if [ -e "public-website" ]; then

      rm -rf "public-website" ;

    fi

    git clone https://github.com/owent/blog-website.git "public-website" ;

    cd "public-website" ;

    ls -A | xargs rm -rf ;

    cp -rf ../public/* ../public/.* ./ ;

    echo "owent.net" > CNAME ;

    ls -A | xargs git add ;

    git -c user.name='travis' -c user.email='deploy@travis-ci.org' commit -m "Delpoy owent.net for $TRAVIS_COMMIT($TRAVIS_COMMIT_MESSAGE)";

    git push -f -q https://owt5008137:$GITHUB_TOKEN@github.com/owent/blog-website HEAD:master ;

cache: 
  apt: true
  ccache: true

# deploy:
#   provider: pages
#   local_dir: public
#   repo: owent/blog-website
#   target_branch: master
#   # keep_history: true
#   keep_history: false
#   fqdn: owent.net
#   project_name: "I'm OWenT"
#   github_token: $GITHUB_TOKEN
#   skip_cleanup: true
#   on:
#     all_branches: true

notifications:
  email:
    recipients:
      - admin@owent.net
      - owt5008137@live.com
    on_success: change
    on_failure: change
  irc:
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"