---
baseURL: "//owent.net"

# include content marked as draft
buildDrafts: false
# include content with publishdate in the future
buildFuture: true
# include content already expired
buildExpired: true
# config file (default is path/config.yaml|json|toml)
config: "config.yaml"
contentDir: "source"
dataDir: "data"
defaultExtension: "html"
defaultLayout: "post"
# Missing translations will default to this content language
defaultContentLanguage: "zh-cn"
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir: false
# The below example will disable all page types and will render nothing.
disableKinds: []
disableLiveReload: false
# Enable GitInfo feature
enableGitInfo: false
# Build robots.txt file
enableRobotsTXT: true
# Do not inject generator meta tag on homepage
disableHugoGeneratorInject: false
# Enable Emoji emoticons support for page content.
# See www.emoji-cheat-sheet.com
enableEmoji: false
# Show a placeholder instead of the default value or an empty string if a translation is missing
enableMissingTranslationPlaceholders: false
footnoteAnchorPrefix: ""
footnoteReturnLinkContents: ""

languageCode: "zh-cn"
layoutDir: "layouts"
# Enable Logging
log: false
# Log File path (if set, logging enabled automatically)
logFile: ""
# "yaml", "toml", "json"
metaDataFormat: "yaml"
# Edit new content with this editor, if provided
newContentEditor: ""
# Don't sync permission mode of files
noChmod: false
# Don't sync modification time of files
noTimes: false
pagination:
  pagerSize: 20
  path: "page"
permalinks:
  post: /:year/:filename

# Pluralize titles in lists using inflect
pluralizeListTitles: true
# Preserve special characters in taxonomy names ("Gérard Depardieu" vs "Gerard Depardieu")
preserveTaxonomyNames: false
# filesystem path to write files to
publishDir: "public"
# Set to true to enable syntax highlighting in code fences with a language tag in markdown
pygmentsCodefences: false
# enables syntax guessing for code fences without specified language
pygmentsCodeFencesGuessSyntax: false
# color-codes for highlighting derived from this style
pygmentsStyle: "github"
# true: use pygments-css or false: color-codes directly
pygmentsUseClasses: false
# A comma separated list of options.
pygmentsOptions: ""
# Set to true to use Pygments instead of the much faster Chroma.
pygmentsUseClassic: false
# maximum number of items in the RSS feed
rssLimit: 100
# default sitemap configuration map
sitemap: sitemap.xml
# filesystem path to read files relative from
source: ""
staticDir:
  - "source/post"
  - "source/static"
# display memory and timing of different steps of the program
stepAnalysis: false
# theme to use (located by default in /themes/THEMENAME/)
themesDir: "themes"
theme: "distinctionpp"
title: "I'm OWenT"
# if true, use /filename.html instead of /filename/
uglyURLs: true
# if true, auto-detect Chinese/Japanese/Korean Languages in the content. (.Summary and .WordCount can work properly in CJKLanguage)
hasCJKLanguage: true
# verbose output
verbose: false
# verbose logging
verboseLog: false
# watch filesystem for changes and recreate as needed
watch: true
ignoreFiles:
  - "README\\.md$"

# custom options

params:
  description: "Challenge Everything"
  author: "OWenT"
  githubuser: "owent"
  sitesource: "https://github.com/owent/blog-hugo"
  favicon: /favicon.ico
  css: ["css/syntax.css"]
  ugly: ".html"
  search:
    url: //www.bing.com/search
    keywork: q
    sitename: q1
    siteprefix: "site:"
  modules:
    importmap:
      "react": "https://cdn.jsdelivr.net/npm/react/+esm"
      "react-bootstrap": "https://cdn.jsdelivr.net/npm/react-bootstrap/+esm"
    module:
      - |
        // import React from "react";
  content:
    footer:
      right: '<a href="https://beian.miit.gov.cn/" target="_blank">沪ICP备2022003252号</a>&nbsp;&nbsp;'
    after_footer:
      - attributes:
          type: "text/javascript"
        content: |
          var _hmt = _hmt || [];
          (function() {
            var hm = document.createElement("script");
            hm.src = "https://hm.baidu.com/hm.js?6a0daf8d58889f1cf55a353867bfdbb0";
            var sdoms = document.getElementsByTagName("script");
            var s = document.getElementsByTagName("script")[sdoms.length - 1]; 
            s.parentNode.appendChild(hm);
          })();
  bootstrap:
    css: https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.min.css
    js: "https://cdn.jsdelivr.net/npm/bootstrap/+esm"
    popper:
      js: "https://cdn.jsdelivr.net/npm/popper.js/+esm"
  highlightjs:
    style: "vs2015" # style name
    langs: [
        "accesslog",
        "armasm",
        "awk",
        "basic",
        "bnf",
        # "cpp",
        "capnproto",
        "cmake",
        "d",
        # "diff",
        "dockerfile",
        "dos",
        "erlang",
        "ebnf",
        # "go",
        "latex",
        # "less",
        "llvm",
        "lua",
        # "php",
        "powershell",
        "protobuf",
        # "python",
        "profile",
        # "typescript",
        "vim",
        # "rust",
        "x86asm",
        "yaml",
      ]
    selector: "pre>code"
    version: "latest"
    url:
      js: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js
      style: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/styles/%STYLE%.min.css
      lang: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/languages/%LANG%.min.js
    options: # options of highlight.js see http://highlightjs.readthedocs.io/en/latest/api.html#configure-options
      tabReplace: "    "
      useBR: false
      #classPrefix: 'hljs-'
      languages: {} # language alias
      ignoreUnescapedHTML: true
      throwUnescapedHTML: false
  katex:
    js: https://cdn.jsdelivr.net/npm/katex/dist/katex.min.js
    css: https://cdn.jsdelivr.net/npm/katex/dist/katex.min.css
    autorender: https://cdn.jsdelivr.net/npm/katex/dist/contrib/auto-render.min.js
  chartjs:
    js: https://cdn.jsdelivr.net/npm/chart.js/dist/chart.umd.min.js
  mermaid:
    js: "https://cdn.jsdelivr.net/npm/mermaid/+esm"
    theme: neutral
  utteranc:
    repo: "owent/blog-website"
    issue_term: "pathname"
    theme: "github-light"
  # styleimport:
  #   delay: 200
  #   urls: ['https://fonts.googleapis.com/css?family=Noto+Sans+SC:400,700&subset=chinese-simplified,japanese', 'https://fonts.googleapis.com/css?family=Roboto+Mono:400,400i,500,500i&subset=latin-ext', 'https://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i&subset=latin-ext']
  adsense:
    code: |
      <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8180054975285991" crossorigin="anonymous"></script>
  metas:
    - name: "baidu-site-verification"
      content: "codeva-4M5iohb9TW"
  ads:
    # menu:
    article:
      # panel_header:
      # panel_footer:
      # before_title:
      # after_title:
      # after_body:
      after_footer: |
        <!-- article_after_footer -->
        <ins class="adsbygoogle ads_infeed"
            style="display:block"
            data-ad-client="ca-pub-8180054975285991"
            data-ad-slot="5599802929"
            data-ad-format="rectangle, horizontal"
            data-full-width-responsive="true"></ins>
        <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
      # before_comments:
      # after_comments:
      after_toc: |
        <!-- after_toc -->
        <ins class="adsbygoogle ads_toc"
            style="display:block"
            data-ad-client="ca-pub-8180054975285991"
            data-ad-slot="1249494377"
            data-ad-format="rectangle, vertical"
            data-full-width-responsive="true"></ins>
        <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
    page:
      after_body: |
        <!-- article_after_footer -->
        <ins class="adsbygoogle ads_infeed"
            style="display:block"
            data-ad-client="ca-pub-8180054975285991"
            data-ad-slot="5599802929"
            data-ad-format="rectangle, horizontal"
            data-full-width-responsive="true"></ins>
        <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
    # archive:
    #   # panel_header:
    #   # panel_footer:
    #   # before_title:
    #   # after_title:
    #   # after_summary:

menus:
  main:
    - Name: "Home"
      Weight: 1
      Identifier: "home"
      pageRef: "/"
    - Name: "Archives"
      Weight: 2
      Identifier: "archives"
      pageRef: "/archives"
    - Name: "About"
      Weight: 3
      Identifier: "about"
      pageRef: "/about"

author:
  name: "OWenT"
  email: "admin@owent.net"

Copyright: '<a rel="license" href="https://github.com/owent/blog-hugo/blob/master/LICENSE.md"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a>'

taxonomies:
  tag: "tags"
  category: "categories"

# services:

services:
  # disqus:
  #   shortname: owent
  googleAnalytics:
    ID: "G-PQEY77BYG1"

markup:
  defaultMarkdownHandler: goldmark
  blackfriday:
    taskLists: true
    smartypants: true
    angledQuotes: false
    fractions: true
    smartDashes: true
    latexDashes: true
    hrefTargetBlank: true
    plainIDAnchors: true
    extensions:
      - noIntraEmphasis
      - tables
      - fencedCode
      - autolink
      - strikethrough
      - laxHtmlBlocks
      - hardLineBreak
      - footnotes
      - noEmptyLineBeforeBlock
    extensionsmask:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
---

