---
baseURL: "//owent.net"

# include content marked as draft
buildDrafts: false
# include content with publishdate in the future
buildFuture: true
# include content already expired
buildExpired: true
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs: true
canonifyURLs: true
# config file (default is path/config.yaml|json|toml)
config: "config.yaml"
contentDir: "source"
dataDir: "data"
defaultExtension: "html"
defaultLayout: "post"
# Missing translations will default to this content language
defaultContentLanguage: "zh-cn"
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir: false
# The below example will disable all page types and will render nothing.
disableKinds: []
disableLiveReload: false
# Enable GitInfo feature
enableGitInfo: false
# Build robots.txt file
enableRobotsTXT: true
# Do not inject generator meta tag on homepage
disableHugoGeneratorInject: false
# Enable Emoji emoticons support for page content.
# See www.emoji-cheat-sheet.com
enableEmoji: false
# Show a placeholder instead of the default value or an empty string if a translation is missing
enableMissingTranslationPlaceholders: false
footnoteAnchorPrefix: ""
footnoteReturnLinkContents: ""

languageCode: "zh-cn"
layoutDir: "layouts"
# Enable Logging
log: false
# Log File path (if set, logging enabled automatically)
logFile: ""
# "yaml", "toml", "json"
metaDataFormat: "yaml"
# Edit new content with this editor, if provided
newContentEditor: ""
# Don't sync permission mode of files
noChmod: false
# Don't sync modification time of files
noTimes: false
paginate: 20
paginatePath: "page"
permalinks:
  post: /:year/:filename

# Pluralize titles in lists using inflect
pluralizeListTitles: true
# Preserve special characters in taxonomy names ("Gérard Depardieu" vs "Gerard Depardieu")
preserveTaxonomyNames: false
# filesystem path to write files to
publishDir: "public"
# Set to true to enable syntax highlighting in code fences with a language tag in markdown
pygmentsCodefences: false
# enables syntax guessing for code fences without specified language
pygmentsCodeFencesGuessSyntax: false
# color-codes for highlighting derived from this style
pygmentsStyle: "github"
# true: use pygments-css or false: color-codes directly
pygmentsUseClasses: false
# A comma separated list of options.
pygmentsOptions: ""
# Set to true to use Pygments instead of the much faster Chroma.
pygmentsUseClassic: false
# maximum number of items in the RSS feed
rssLimit: 100
# default sitemap configuration map
sitemap: sitemap.xml
# filesystem path to read files relative from
source: ""
staticDir: "source/post"
# display memory and timing of different steps of the program
stepAnalysis: false
# theme to use (located by default in /themes/THEMENAME/)
themesDir: "themes"
theme: "distinctionpp"
title: "I'm OWenT"
# if true, use /filename.html instead of /filename/
uglyURLs: true
# if true, auto-detect Chinese/Japanese/Korean Languages in the content. (.Summary and .WordCount can work properly in CJKLanguage)
hasCJKLanguage: true
# verbose output
verbose: false
# verbose logging
verboseLog: false
# watch filesystem for changes and recreate as needed
watch: true
ignoreFiles:
  - "README\\.md$"

# custom options

params:
  description: "Challenge Everything"
  author: "OWenT"
  githubuser: "owt5008137"
  sitesource: "https://github.com/owent/blog-hugo"
  favicon: /favicon.ico
  css: ["css/syntax.css"]
  ugly: ".html"
  search:
    url: //www.bing.com/search
    keywork: q
    sitename: q1
    siteprefix: "site:"
  bootstrap:
    # js: //cdn.bootcss.com/bootstrap/4.5.3/js/bootstrap.min.js
    js: //unpkg.com/bootstrap@latest/dist/js/bootstrap.min.js
    # css: //cdn.bootcss.com/bootstrap/4.5.3/css/bootstrap.min.css
    css: //unpkg.com/bootstrap@latest/dist/css/bootstrap.min.css
    popper:
      js: //unpkg.com/popper.js@latest/dist/umd/popper.min.js
  highlightjs:
    style: "vs2015" # style name
    langs:
      [
        "bash",
        "cpp",
        "capnproto",
        "cmake",
        "d",
        "diff",
        "dos",
        "erlang",
        "go",
        "less",
        "lua",
        "php",
        "powershell",
        "protobuf",
        "profile",
        "typescript",
        "vim",
        "rust",
      ]
    selector: "pre>code"
    version: "10.4.1"
    url: #
      # js: "//cdn.bootcss.com/highlight.js/%VERSION%/highlight.min.js"
      js: //cdnjs.cloudflare.com/ajax/libs/highlight.js/%VERSION%/highlight.min.js
      # style: "//cdn.bootcss.com/highlight.js/%VERSION%/styles/%STYLE%.min.css"
      style: //cdnjs.cloudflare.com/ajax/libs/highlight.js/%VERSION%/styles/%STYLE%.min.css
      # lang: "//cdn.bootcss.com/highlight.js/%VERSION%/languages/%LANG%.min.js"
      lang: //cdnjs.cloudflare.com/ajax/libs/highlight.js/%VERSION%/languages/%LANG%.min.js
    options: # options of highlight.js see http://highlightjs.readthedocs.io/en/latest/api.html#configure-options
      tabReplace: "    "
      useBR: false
      #classPrefix: 'hljs-'
      languages: {} # language alias
  katex:
    js: //unpkg.com/katex@latest/dist/katex.min.js
    css: //unpkg.com/katex@latest/dist/katex.min.css
    autorender: //unpkg.com/katex@latest/dist/contrib/auto-render.min.js
  jquery:
    js: //unpkg.com/jquery@latest/dist/jquery.slim.min.js
    migrate: //unpkg.com/jquery-migrate@latest/dist/jquery-migrate.min.js
  chartjs:
    js: //unpkg.com/chart.js@latest/dist/Chart.min.js
  mermaid:
    js: //unpkg.com/mermaid@latest/dist/mermaid.min.js
  # styleimport:
  #   delay: 200
  #   urls: ['https://fonts.googleapis.com/css?family=Noto+Sans+SC:400,700&subset=chinese-simplified,japanese', 'https://fonts.googleapis.com/css?family=Roboto+Mono:400,400i,500,500i&subset=latin-ext', 'https://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i&subset=latin-ext']

menu:
  main:
    - Name: "Home"
      Weight: 1
      Identifier: "home"
      URL: "/"
    - Name: "Archives"
      Weight: 2
      Identifier: "archives"
      URL: "/archives.html"
    - Name: "About"
      Weight: 3
      Identifier: "about"
      URL: "/about.html"

author:
  name: "OWenT"
  email: "admin@owent.net"

taxonomies:
  tag: "tags"
  category: "categories"

DisqusShortname: owent
googleAnalytics: "UA-19298704-1"

blackfriday:
  taskLists: true
  smartypants: true
  angledQuotes: false
  fractions: true
  smartDashes: true
  latexDashes: true
  hrefTargetBlank: true
  plainIDAnchors: true
  extensions:
    - noIntraEmphasis
    - tables
    - fencedCode
    - autolink
    - strikethrough
    - laxHtmlBlocks
    - hardLineBreak
    - footnotes
    - noEmptyLineBeforeBlock
  extensionsmask:
---

